#!/usr/bin/env bash
# Render production .env from runtime environment variables (CI/CD friendly).
set -euo pipefail
cd "$(dirname "$0")/.."

log() { printf '%s\n' "$*"; }
die() { log "ERROR: $*"; exit 1; }

require_var() {
  local name="$1"
  if [ -z "${!name:-}" ]; then
    die "Required env var is missing: ${name}"
  fi
}

# Required for production.
require_var VPN_PANEL_DOMAIN

# Optional with defaults.
CADDYFILE_PATH="${CADDYFILE_PATH:-Caddyfile.prod}"
CADDY_HTTP_PORT="${CADDY_HTTP_PORT:-80}"
CADDY_HTTPS_PORT="${CADDY_HTTPS_PORT:-443}"
XRAY_PORT="${XRAY_PORT:-8443}"
WG_PORT="${WG_PORT:-51820}"
ADMIN_USERNAME="${ADMIN_USERNAME:-admin}"
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@example.com}"
APP_SECRET_KEY_FILE="${APP_SECRET_KEY_FILE:-}"
ADMIN_PASSWORD_FILE="${ADMIN_PASSWORD_FILE:-}"
CAPACITY_TARGET_ACTIVE_USERS="${CAPACITY_TARGET_ACTIVE_USERS:-15}"
CAPACITY_CPU_WARN_P95="${CAPACITY_CPU_WARN_P95:-70}"
CAPACITY_CPU_CRIT_P95="${CAPACITY_CPU_CRIT_P95:-80}"
CAPACITY_RAM_WARN_P95="${CAPACITY_RAM_WARN_P95:-80}"
CAPACITY_RAM_CRIT_P95="${CAPACITY_RAM_CRIT_P95:-85}"
CAPACITY_DISK_WARN_P95="${CAPACITY_DISK_WARN_P95:-85}"
CAPACITY_DISK_CRIT_P95="${CAPACITY_DISK_CRIT_P95:-92}"
DASHBOARD_REFRESH_SECONDS="${DASHBOARD_REFRESH_SECONDS:-30}"
LOGIN_MAX_ATTEMPTS="${LOGIN_MAX_ATTEMPTS:-5}"
LOGIN_WINDOW_MINUTES="${LOGIN_WINDOW_MINUTES:-10}"
LOGIN_LOCK_MINUTES="${LOGIN_LOCK_MINUTES:-15}"
SECURITY_GEOIP_ENABLED="${SECURITY_GEOIP_ENABLED:-1}"
SECURITY_GEOIP_TIMEOUT_SECONDS="${SECURITY_GEOIP_TIMEOUT_SECONDS:-1.5}"
SECURITY_DEFAULT_BLOCK_SECONDS="${SECURITY_DEFAULT_BLOCK_SECONDS:-900}"
SECURITY_HTTP_WINDOW_SECONDS="${SECURITY_HTTP_WINDOW_SECONDS:-10}"
SECURITY_HTTP_MAX_REQUESTS="${SECURITY_HTTP_MAX_REQUESTS:-120}"
SECURITY_PROBE_PATH_THRESHOLD="${SECURITY_PROBE_PATH_THRESHOLD:-12}"
SECURITY_BLOCK_SECONDS_DDOS="${SECURITY_BLOCK_SECONDS_DDOS:-600}"
SECURITY_BLOCK_SECONDS_BRUTE="${SECURITY_BLOCK_SECONDS_BRUTE:-900}"
SECURITY_SERVER_CHECK_INTERVAL_SECONDS="${SECURITY_SERVER_CHECK_INTERVAL_SECONDS:-60}"
SECURITY_SERVER_EVENT_COOLDOWN_SECONDS="${SECURITY_SERVER_EVENT_COOLDOWN_SECONDS:-300}"

if [ -z "${APP_SECRET_KEY_FILE}" ] && [ -z "${APP_SECRET_KEY:-}" ]; then
  die "Required env var is missing: APP_SECRET_KEY or APP_SECRET_KEY_FILE"
fi
if [ -z "${ADMIN_PASSWORD_FILE}" ] && [ -z "${ADMIN_PASSWORD:-}" ]; then
  die "Required env var is missing: ADMIN_PASSWORD or ADMIN_PASSWORD_FILE"
fi

cat > .env <<EOF
CADDYFILE_PATH=${CADDYFILE_PATH}
VPN_PANEL_DOMAIN=${VPN_PANEL_DOMAIN}
CADDY_HTTP_PORT=${CADDY_HTTP_PORT}
CADDY_HTTPS_PORT=${CADDY_HTTPS_PORT}
XRAY_PORT=${XRAY_PORT}
WG_PORT=${WG_PORT}
ADMIN_USERNAME=${ADMIN_USERNAME}
ADMIN_EMAIL=${ADMIN_EMAIL}
CAPACITY_TARGET_ACTIVE_USERS=${CAPACITY_TARGET_ACTIVE_USERS}
CAPACITY_CPU_WARN_P95=${CAPACITY_CPU_WARN_P95}
CAPACITY_CPU_CRIT_P95=${CAPACITY_CPU_CRIT_P95}
CAPACITY_RAM_WARN_P95=${CAPACITY_RAM_WARN_P95}
CAPACITY_RAM_CRIT_P95=${CAPACITY_RAM_CRIT_P95}
CAPACITY_DISK_WARN_P95=${CAPACITY_DISK_WARN_P95}
CAPACITY_DISK_CRIT_P95=${CAPACITY_DISK_CRIT_P95}
DASHBOARD_REFRESH_SECONDS=${DASHBOARD_REFRESH_SECONDS}
LOGIN_MAX_ATTEMPTS=${LOGIN_MAX_ATTEMPTS}
LOGIN_WINDOW_MINUTES=${LOGIN_WINDOW_MINUTES}
LOGIN_LOCK_MINUTES=${LOGIN_LOCK_MINUTES}
SECURITY_GEOIP_ENABLED=${SECURITY_GEOIP_ENABLED}
SECURITY_GEOIP_TIMEOUT_SECONDS=${SECURITY_GEOIP_TIMEOUT_SECONDS}
SECURITY_DEFAULT_BLOCK_SECONDS=${SECURITY_DEFAULT_BLOCK_SECONDS}
SECURITY_HTTP_WINDOW_SECONDS=${SECURITY_HTTP_WINDOW_SECONDS}
SECURITY_HTTP_MAX_REQUESTS=${SECURITY_HTTP_MAX_REQUESTS}
SECURITY_PROBE_PATH_THRESHOLD=${SECURITY_PROBE_PATH_THRESHOLD}
SECURITY_BLOCK_SECONDS_DDOS=${SECURITY_BLOCK_SECONDS_DDOS}
SECURITY_BLOCK_SECONDS_BRUTE=${SECURITY_BLOCK_SECONDS_BRUTE}
SECURITY_SERVER_CHECK_INTERVAL_SECONDS=${SECURITY_SERVER_CHECK_INTERVAL_SECONDS}
SECURITY_SERVER_EVENT_COOLDOWN_SECONDS=${SECURITY_SERVER_EVENT_COOLDOWN_SECONDS}
EOF

if [ -n "${APP_SECRET_KEY_FILE}" ]; then
  printf 'APP_SECRET_KEY_FILE=%s\n' "${APP_SECRET_KEY_FILE}" >> .env
else
  printf 'APP_SECRET_KEY=%s\n' "${APP_SECRET_KEY}" >> .env
fi

if [ -n "${ADMIN_PASSWORD_FILE}" ]; then
  printf 'ADMIN_PASSWORD_FILE=%s\n' "${ADMIN_PASSWORD_FILE}" >> .env
else
  printf 'ADMIN_PASSWORD=%s\n' "${ADMIN_PASSWORD}" >> .env
fi

chmod 600 .env
log "Rendered .env from runtime environment."
